# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 022678d50e7ffce0b802cf48861ded19ba59edc676d6963213a164a63f634b239530c68a14f3b56c729140b2190a0e8a27bd782c9602a0895a0d3dc807ca9968

test:
  secret_key_base: 5b698c3545468b232bc42e45b1a174466bfa66df587de54633a5f8d6d1db0eeee57df2ae7ec7556559c830a7a89038b1db56b60adcdd54b5d03a5e1b0d73ff97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
